/*
    DbInda — seguimiento del importador.

    Ejecución MANUAL. La aplicación NO crea estas tablas al arrancar.
    Repetible: no recrea objetos que ya existen.
    No modifica TICKET ni TICKET_RECEPCION.

    Las fechas *_UTC son UTC sin zona. No convierten FECHA_PROCESADO
    ni el resto de fechas históricas, que siguen siendo la hora local
    con la que la aplicación las escribió.

    No hay clave foránea hacia TICKET_RECEPCION: un intento de conexión
    puede guardarse antes de que exista una recepción.

    Una parada abrupta no escribe FECHA_PARADA_UTC. Se detecta porque
    ESTADO sigue ACTIVA y FECHA_SENAL_UTC queda antigua. Ver la vista
    VW_IMPORTADOR_EJECUCION_SIN_SENAL.
*/

USE [TicketsTPV];
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.IMPORTADOR_EJECUCION', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.IMPORTADOR_EJECUCION
    (
        ID_EJECUCION          UNIQUEIDENTIFIER NOT NULL,
        SECUENCIA             BIGINT           NOT NULL,
        NOMBRE_APLICACION     NVARCHAR(100)    NOT NULL,
        NOMBRE_INSTANCIA      NVARCHAR(200)    NOT NULL,
        EQUIPO                NVARCHAR(128)    NOT NULL,
        ID_PROCESO            INT              NOT NULL,
        VERSION_APLICACION    NVARCHAR(64)     NOT NULL,
        FECHA_INICIO_UTC      DATETIME2(3)     NOT NULL,
        FECHA_SENAL_UTC       DATETIME2(3)     NOT NULL,
        FECHA_PARADA_UTC      DATETIME2(3)     NULL,
        ESTADO                VARCHAR(32)      NOT NULL,
        MOTIVO_FINALIZACION   NVARCHAR(400)    NULL,

        CONSTRAINT PK_IMPORTADOR_EJECUCION PRIMARY KEY CLUSTERED (ID_EJECUCION),
        CONSTRAINT CK_IMPORTADOR_EJECUCION_ESTADO CHECK (ESTADO IN ('ACTIVA', 'DETENIDA'))
    );
END
GO

IF OBJECT_ID(N'dbo.IMPORTADOR_INTENTO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.IMPORTADOR_INTENTO
    (
        ID_INTENTO                    UNIQUEIDENTIFIER NOT NULL,
        SECUENCIA                     BIGINT           NOT NULL,
        ID_EJECUCION                  UNIQUEIDENTIFIER NOT NULL,
        ID_RECEPCION                  BIGINT           NULL,
        ID_TICKET                     BIGINT           NULL,
        NOMBRE_FICHERO                NVARCHAR(300)    NOT NULL,
        RUTA_ORIGEN                   NVARCHAR(1024)   NOT NULL,
        CORRELACION_ORIGEN            CHAR(64)         NOT NULL,
        HASH_SHA256                   CHAR(64)         NULL,
        TIENDA                        INT              NULL,
        TPV                           INT              NULL,
        NUMERO_INTENTO                INT              NULL,
        TIPO_INTENTO                  VARCHAR(16)      NOT NULL,
        FECHA_INICIO_UTC              DATETIME2(3)     NOT NULL,
        FECHA_FIN_UTC                 DATETIME2(3)     NULL,
        DURACION_MS                   INT              NULL,
        FASE                          VARCHAR(40)      NOT NULL,
        RESULTADO                     VARCHAR(40)      NOT NULL,
        CATEGORIA_ERROR               VARCHAR(40)      NULL,
        CODIGO_ERROR                  VARCHAR(64)      NULL,
        MENSAJE                       NVARCHAR(1000)   NULL,
        ID_DETALLE_TECNICO            UNIQUEIDENTIFIER NULL,
        FECHA_PROXIMO_REINTENTO_UTC   DATETIME2(3)     NULL,
        REGISTROS_CONFIRMADOS         INT              NULL,

        CONSTRAINT PK_IMPORTADOR_INTENTO PRIMARY KEY CLUSTERED (ID_INTENTO),
        CONSTRAINT CK_IMPORTADOR_INTENTO_TIPO CHECK (
            (TIPO_INTENTO = 'CONEXION' AND ID_RECEPCION IS NULL AND NUMERO_INTENTO IS NULL)
            OR (TIPO_INTENTO = 'RECEPCION' AND NUMERO_INTENTO >= 1)
        ),
        CONSTRAINT CK_IMPORTADOR_INTENTO_RESULTADO CHECK (RESULTADO IN (
            'EN_CURSO', 'IMPORTADO', 'IMPORTADO_CON_ADVERTENCIAS', 'DUPLICADO', 'CONFLICTO',
            'ERROR_XML', 'ERROR_PERMANENTE', 'ERROR_SQL', 'SQL_NO_DISPONIBLE', 'INCIERTO'
        )),
        CONSTRAINT CK_IMPORTADOR_INTENTO_HASH CHECK (
            HASH_SHA256 IS NULL OR (LEN(HASH_SHA256) = 64 AND HASH_SHA256 NOT LIKE '%[^0-9A-Fa-f]%')
        ),
        CONSTRAINT CK_IMPORTADOR_INTENTO_CORRELACION CHECK (
            LEN(CORRELACION_ORIGEN) = 64 AND CORRELACION_ORIGEN NOT LIKE '%[^0-9A-Fa-f]%'
        )
    );
END
GO

IF OBJECT_ID(N'dbo.IMPORTADOR_EVENTO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.IMPORTADOR_EVENTO
    (
        ID_EVENTO       UNIQUEIDENTIFIER NOT NULL,
        SECUENCIA       BIGINT           NOT NULL,
        FECHA_UTC       DATETIME2(3)     NOT NULL,
        SEVERIDAD       VARCHAR(16)      NOT NULL,
        TIPO            VARCHAR(64)      NOT NULL,
        ID_EJECUCION    UNIQUEIDENTIFIER NULL,
        ID_INTENTO      UNIQUEIDENTIFIER NULL,
        ID_RECEPCION    BIGINT           NULL,
        ID_TICKET       BIGINT           NULL,
        RUTA_ORIGEN     NVARCHAR(1024)   NULL,
        FASE            VARCHAR(40)      NULL,
        DETALLE         NVARCHAR(2000)   NULL,

        CONSTRAINT PK_IMPORTADOR_EVENTO PRIMARY KEY CLUSTERED (ID_EVENTO),
        CONSTRAINT CK_IMPORTADOR_EVENTO_SEVERIDAD CHECK (SEVERIDAD IN ('Information', 'Warning', 'Error'))
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_EJECUCION_SENAL' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_EJECUCION'))
    CREATE INDEX IX_IMPORTADOR_EJECUCION_SENAL
        ON dbo.IMPORTADOR_EJECUCION (FECHA_SENAL_UTC)
        WHERE FECHA_PARADA_UTC IS NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_INTENTO_RESULTADO_FIN' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_INTENTO'))
    CREATE INDEX IX_IMPORTADOR_INTENTO_RESULTADO_FIN
        ON dbo.IMPORTADOR_INTENTO (RESULTADO, FECHA_FIN_UTC)
        INCLUDE (TIENDA, TPV, ID_RECEPCION, DURACION_MS);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_INTENTO_RECEPCION' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_INTENTO'))
    CREATE INDEX IX_IMPORTADOR_INTENTO_RECEPCION
        ON dbo.IMPORTADOR_INTENTO (ID_RECEPCION, FECHA_INICIO_UTC)
        WHERE ID_RECEPCION IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_INTENTO_ORIGEN' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_INTENTO'))
    CREATE INDEX IX_IMPORTADOR_INTENTO_ORIGEN
        ON dbo.IMPORTADOR_INTENTO (CORRELACION_ORIGEN, FECHA_INICIO_UTC);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_INTENTO_ABIERTOS' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_INTENTO'))
    CREATE INDEX IX_IMPORTADOR_INTENTO_ABIERTOS
        ON dbo.IMPORTADOR_INTENTO (FECHA_INICIO_UTC)
        WHERE RESULTADO = 'EN_CURSO';
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_EVENTO_FECHA' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_EVENTO'))
    CREATE INDEX IX_IMPORTADOR_EVENTO_FECHA
        ON dbo.IMPORTADOR_EVENTO (FECHA_UTC, SECUENCIA);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_EVENTO_RECEPCION' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_EVENTO'))
    CREATE INDEX IX_IMPORTADOR_EVENTO_RECEPCION
        ON dbo.IMPORTADOR_EVENTO (ID_RECEPCION, FECHA_UTC)
        WHERE ID_RECEPCION IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_IMPORTADOR_EVENTO_INTENTO' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_EVENTO'))
    CREATE INDEX IX_IMPORTADOR_EVENTO_INTENTO
        ON dbo.IMPORTADOR_EVENTO (ID_INTENTO, SECUENCIA)
        WHERE ID_INTENTO IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_IMPORTADOR_EVENTO_SECUENCIA' AND object_id = OBJECT_ID(N'dbo.IMPORTADOR_EVENTO'))
    CREATE UNIQUE INDEX UX_IMPORTADOR_EVENTO_SECUENCIA
        ON dbo.IMPORTADOR_EVENTO (ID_EJECUCION, SECUENCIA)
        WHERE ID_EJECUCION IS NOT NULL;
GO
