/*
    Vistas de solo lectura del seguimiento.
    Repetible: CREATE OR ALTER VIEW.
    No las ejecuta la aplicación.

    "Hoy" en estas vistas es el día civil de Romance Standard Time
    (Europe/Madrid en identificadores IANA). Las columnas *_UTC se
    convierten de forma explícita. FECHA_PROCESADO no se convierte:
    es la marca local que ya guardaba la aplicación.

    Una importación nueva es solo PROCESADO o PROCESADO_CON_ADVERTENCIAS
    (RESULTADO IMPORTADO o IMPORTADO_CON_ADVERTENCIAS).
    Duplicados y conflictos no cuentan como tickets nuevos.

    FECHA_PROCESADO no es el instante exacto del COMMIT.
    FECHA_EXPEDICION no es la fecha de importación.

    Los datos anteriores al despliegue de sql/05_CreateTracking.sql
    solo aparecen en las columnas históricas de TICKET_RECEPCION.
*/

USE [TicketsTPV];
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_ESTADO
AS
SELECT TOP (1)
    e.ID_EJECUCION,
    e.NOMBRE_APLICACION,
    e.NOMBRE_INSTANCIA,
    e.EQUIPO,
    e.ID_PROCESO,
    e.VERSION_APLICACION,
    e.FECHA_INICIO_UTC,
    e.FECHA_SENAL_UTC,
    e.FECHA_PARADA_UTC,
    e.ESTADO,
    e.MOTIVO_FINALIZACION,
    DATEDIFF(SECOND, e.FECHA_SENAL_UTC, SYSUTCDATETIME()) AS SEGUNDOS_SIN_SENAL,
    CASE
        WHEN e.FECHA_PARADA_UTC IS NOT NULL THEN e.ESTADO
        WHEN e.FECHA_SENAL_UTC < DATEADD(MINUTE, -3, SYSUTCDATETIME()) THEN 'POSIBLE_INTERRUPCION'
        ELSE e.ESTADO
    END AS ESTADO_OBSERVADO
FROM dbo.IMPORTADOR_EJECUCION e
ORDER BY e.FECHA_INICIO_UTC DESC;
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_EJECUCION_SIN_SENAL
AS
SELECT
    e.ID_EJECUCION,
    e.EQUIPO,
    e.NOMBRE_INSTANCIA,
    e.FECHA_INICIO_UTC,
    e.FECHA_SENAL_UTC,
    DATEDIFF(SECOND, e.FECHA_SENAL_UTC, SYSUTCDATETIME()) AS SEGUNDOS_SIN_SENAL
FROM dbo.IMPORTADOR_EJECUCION e
WHERE e.FECHA_PARADA_UTC IS NULL
  AND e.FECHA_SENAL_UTC < DATEADD(MINUTE, -3, SYSUTCDATETIME());
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_ULTIMA_IMPORTACION
AS
SELECT
    (
        SELECT MAX(i.FECHA_FIN_UTC)
        FROM dbo.IMPORTADOR_INTENTO i
        WHERE i.RESULTADO IN ('IMPORTADO', 'IMPORTADO_CON_ADVERTENCIAS')
          AND i.FECHA_FIN_UTC IS NOT NULL
    ) AS ULTIMA_IMPORTACION_UTC,
    (
        SELECT MAX(r.FECHA_PROCESADO)
        FROM dbo.TICKET_RECEPCION r
        WHERE r.ESTADO IN ('PROCESADO', 'PROCESADO_CON_ADVERTENCIAS')
    ) AS ULTIMA_FECHA_PROCESADO_LOCAL;
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_ULTIMA_POR_TIENDA_TPV
AS
SELECT
    COALESCE(n.TIENDA, h.TIENDA) AS TIENDA,
    COALESCE(n.TPV, h.TPV) AS TPV,
    n.ULTIMA_IMPORTACION_UTC,
    h.ULTIMA_FECHA_PROCESADO_LOCAL
FROM
(
    SELECT TIENDA, TPV, MAX(FECHA_FIN_UTC) AS ULTIMA_IMPORTACION_UTC
    FROM dbo.IMPORTADOR_INTENTO
    WHERE RESULTADO IN ('IMPORTADO', 'IMPORTADO_CON_ADVERTENCIAS')
      AND TIENDA IS NOT NULL
      AND TPV IS NOT NULL
      AND FECHA_FIN_UTC IS NOT NULL
    GROUP BY TIENDA, TPV
) n
FULL OUTER JOIN
(
    SELECT TIENDA_FICHERO AS TIENDA, TPV_FICHERO AS TPV, MAX(FECHA_PROCESADO) AS ULTIMA_FECHA_PROCESADO_LOCAL
    FROM dbo.TICKET_RECEPCION
    WHERE ESTADO IN ('PROCESADO', 'PROCESADO_CON_ADVERTENCIAS')
      AND TIENDA_FICHERO IS NOT NULL
      AND TPV_FICHERO IS NOT NULL
    GROUP BY TIENDA_FICHERO, TPV_FICHERO
) h
    ON h.TIENDA = n.TIENDA AND h.TPV = n.TPV;
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_RESUMEN_HOY
AS
SELECT
    d.HOY_MADRID,
    SUM(CASE WHEN i.RESULTADO IN ('IMPORTADO', 'IMPORTADO_CON_ADVERTENCIAS') THEN 1 ELSE 0 END) AS IMPORTACIONES_NUEVAS,
    SUM(CASE WHEN i.RESULTADO = 'DUPLICADO' THEN 1 ELSE 0 END) AS DUPLICADOS,
    SUM(CASE WHEN i.RESULTADO = 'CONFLICTO' THEN 1 ELSE 0 END) AS CONFLICTOS,
    SUM(CASE WHEN i.RESULTADO = 'IMPORTADO_CON_ADVERTENCIAS' THEN 1 ELSE 0 END) AS CON_ADVERTENCIAS,
    SUM(CASE WHEN i.RESULTADO IN ('ERROR_XML', 'ERROR_PERMANENTE', 'ERROR_SQL', 'SQL_NO_DISPONIBLE') THEN 1 ELSE 0 END) AS ERRORES
FROM
(
    SELECT CAST(SYSUTCDATETIME() AT TIME ZONE 'UTC' AT TIME ZONE 'Romance Standard Time' AS date) AS HOY_MADRID
) d
LEFT JOIN dbo.IMPORTADOR_INTENTO i
    ON i.FECHA_FIN_UTC IS NOT NULL
   AND CAST(i.FECHA_FIN_UTC AT TIME ZONE 'UTC' AT TIME ZONE 'Romance Standard Time' AS date) = d.HOY_MADRID
GROUP BY d.HOY_MADRID;
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_ERRORES_ABIERTOS
AS
SELECT
    r.ID_RECEPCION,
    r.ESTADO,
    r.ESTADO_ARCHIVO,
    r.NOMBRE_FICHERO,
    r.RUTA_ORIGEN,
    r.TIENDA_FICHERO,
    r.TPV_FICHERO,
    r.NUMERO_INTENTO,
    r.FECHA_ULTIMO_INTENTO,
    r.MENSAJE_ERROR
FROM dbo.TICKET_RECEPCION r
WHERE r.ESTADO IN ('ERROR_SQL', 'ERROR_XML', 'ERROR_PERMANENTE', 'ERROR_TEMPORAL', 'PENDIENTE', 'PROCESANDO');
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_ERRORES_HISTORICOS
AS
SELECT
    i.ID_INTENTO,
    i.ID_RECEPCION,
    i.ID_EJECUCION,
    i.RUTA_ORIGEN,
    i.RESULTADO,
    i.NUMERO_INTENTO,
    i.FECHA_INICIO_UTC,
    i.FECHA_FIN_UTC,
    i.CATEGORIA_ERROR,
    i.CODIGO_ERROR,
    i.MENSAJE
FROM dbo.IMPORTADOR_INTENTO i
WHERE i.RESULTADO IN ('ERROR_XML', 'ERROR_PERMANENTE', 'ERROR_SQL', 'SQL_NO_DISPONIBLE', 'INCIERTO');
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_INTENTOS_RECUPERADOS
AS
SELECT
    ok.ID_INTENTO AS ID_INTENTO_OK,
    ok.ID_RECEPCION,
    ok.CORRELACION_ORIGEN,
    ok.FECHA_FIN_UTC AS FIN_OK_UTC,
    prev.ID_INTENTO AS ID_INTENTO_PREVIO,
    prev.RESULTADO AS RESULTADO_PREVIO,
    prev.MENSAJE AS MENSAJE_PREVIO,
    prev.FECHA_FIN_UTC AS FIN_PREVIO_UTC
FROM dbo.IMPORTADOR_INTENTO ok
INNER JOIN dbo.IMPORTADOR_INTENTO prev
    ON prev.CORRELACION_ORIGEN = ok.CORRELACION_ORIGEN
   AND prev.FECHA_INICIO_UTC < ok.FECHA_INICIO_UTC
   AND prev.RESULTADO IN ('ERROR_SQL', 'SQL_NO_DISPONIBLE', 'INCIERTO')
WHERE ok.RESULTADO IN ('IMPORTADO', 'IMPORTADO_CON_ADVERTENCIAS');
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_CONFLICTOS
AS
SELECT
    r.ID_RECEPCION,
    r.ID_TICKET,
    r.ID_RECEPCION_ORIGINAL,
    r.NOMBRE_FICHERO,
    r.RUTA_ORIGEN,
    r.HASH_SHA256,
    r.HASH_TICKET_ASOCIADO,
    r.TIENDA_FICHERO,
    r.TPV_FICHERO,
    r.FECHA_PROCESADO,
    r.NUM_FACTURA_FICHERO
FROM dbo.TICKET_RECEPCION r
WHERE r.ESTADO = 'CONFLICTO_MISMA_FACTURA';
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_ARCHIVADO_PENDIENTE
AS
SELECT
    r.ID_RECEPCION,
    r.ESTADO,
    r.ESTADO_ARCHIVO,
    r.RUTA_ORIGEN,
    r.RUTA_DESTINO_PREVISTA,
    r.RUTA_FINAL,
    r.FECHA_ULTIMO_INTENTO,
    r.FECHA_PROCESADO
FROM dbo.TICKET_RECEPCION r
WHERE r.ESTADO_ARCHIVO IN ('ARCHIVANDO', 'ERROR_ARCHIVO')
   OR (
        r.ESTADO_ARCHIVO = 'PENDIENTE'
        AND r.ESTADO IN ('PROCESADO', 'PROCESADO_CON_ADVERTENCIAS', 'DUPLICADO', 'CONFLICTO_MISMA_FACTURA', 'ERROR_XML', 'ERROR_PERMANENTE')
      );
GO

CREATE OR ALTER VIEW dbo.VW_IMPORTADOR_RENDIMIENTO_HORA
AS
SELECT
    DATEADD(HOUR, DATEDIFF(HOUR, CONVERT(datetime2(3), '2000-01-01'), i.FECHA_FIN_UTC), CONVERT(datetime2(3), '2000-01-01')) AS HORA_UTC,
    COUNT(*) AS INTENTOS_CERRADOS,
    SUM(CASE WHEN i.RESULTADO IN ('IMPORTADO', 'IMPORTADO_CON_ADVERTENCIAS') THEN 1 ELSE 0 END) AS IMPORTACIONES_NUEVAS,
    AVG(i.DURACION_MS) AS DURACION_MEDIA_MS,
    MAX(i.DURACION_MS) AS DURACION_MAX_MS
FROM dbo.IMPORTADOR_INTENTO i
WHERE i.FECHA_FIN_UTC IS NOT NULL
  AND i.DURACION_MS IS NOT NULL
GROUP BY DATEADD(HOUR, DATEDIFF(HOUR, CONVERT(datetime2(3), '2000-01-01'), i.FECHA_FIN_UTC), CONVERT(datetime2(3), '2000-01-01'));
GO
